export const PREFERENCE_QUESTIONS = [
  {
    questionId: 'genre',
    title: 'Любимый жанр',
    description: 'Выберите основные жанры',
    type: 'select',
    options: [
      { value: 'Fantasy', weight: 2 },
      { value: 'Sci-Fi', weight: 2 },
      { value: 'Drama', weight: 1 },
      { value: 'Horror', weight: 1 },
    ],
  },
  {
    questionId: 'mood',
    title: 'Настроение книги',
    description: 'Какое настроение вам ближе?',
    type: 'select',
    options: [
      { value: 'Light', weight: -1 },
      { value: 'Neutral', weight: 0 },
      { value: 'Dark', weight: 1 },
    ],
  },
  {
    questionId: 'length',
    title: 'Объём книги',
    description: 'Предпочтительная длина',
    type: 'select',
    options: [
      { value: 'Short', weight: -1 },
      { value: 'Medium', weight: 0 },
      { value: 'Long', weight: 1 },
    ],
  },
  {
    questionId: 'setting',
    title: 'Место действия',
    description: 'Где вы любите, чтобы происходила история?',
    type: 'select',
    options: [
      { value: 'Real world', weight: 1 },
      { value: 'Fantasy world', weight: 2 },
      { value: 'Space', weight: 2 },
      { value: 'Historical', weight: 1 },
    ],
  },
  {
    questionId: 'protagonist',
    title: 'Главный герой',
    description: 'Какие персонажи вам интересны?',
    type: 'select',
    options: [
      { value: 'Adult', weight: 1 },
      { value: 'Teen', weight: 1 },
      { value: 'Animal', weight: 0 },
      { value: 'Supernatural', weight: 2 },
    ],
  },
  {
    questionId: 'pacing',
    title: 'Темп истории',
    description: 'Какой темп вам нравится?',
    type: 'select',
    options: [
      { value: 'Slow', weight: -1 },
      { value: 'Moderate', weight: 0 },
      { value: 'Fast', weight: 1 },
    ],
  },
  {
    questionId: 'complexity',
    title: 'Сложность сюжета',
    description: 'Предпочтительная сложность',
    type: 'select',
    options: [
      { value: 'Simple', weight: -1 },
      { value: 'Moderate', weight: 0 },
      { value: 'Complex', weight: 1 },
    ],
  },
  {
    questionId: 'era',
    title: 'Временной период',
    description: 'В какой эпохе происходят события?',
    type: 'select',
    options: [
      { value: 'Modern', weight: 0 },
      { value: 'Medieval', weight: 1 },
      { value: 'Future', weight: 2 },
      { value: 'Ancient', weight: 1 },
    ],
  },
  {
    questionId: 'theme',
    title: 'Тема книги',
    description: 'Какие темы вам интересны?',
    type: 'select',
    options: [
      { value: 'Adventure', weight: 2 },
      { value: 'Romance', weight: 1 },
      { value: 'Mystery', weight: 1 },
      { value: 'Horror', weight: 2 },
    ],
  },
  {
    questionId: 'tone',
    title: 'Тон книги',
    description: 'Какой тон вам ближе?',
    type: 'select',
    options: [
      { value: 'Humorous', weight: -1 },
      { value: 'Serious', weight: 1 },
      { value: 'Dark', weight: 2 },
    ],
  },
];
